backend:
  name: github
  repo: valyamasterov/valyafm
  branch: main
  base_url: http://localhost:1313
  auth_scope: repo

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "entries"
    label: "Entries"
    folder: "content/entries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
